[package]
name = "my_web_app"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["json"] }
hyper = { version = "0.14.32", features = ["server"] }  # Enable the `server` feature
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["full"] }